platform :ios, '5.0'
pod 'RHAddressBook'
pod 'TITokenField', :git => 'https://github.com/imcj/TITokenField.git'
pod 'AFNetworking'
pod 'JSMessagesViewController', :git => 'https://github.com/maiduo/MessagesTableViewController.git'
pod 'EGOTableViewPullRefresh'
pod 'MBProgressHUD'